const base='/app/fnvpn/api/';
const el=id=>document.getElementById(id);
let state=null, report=null, busy=false;
const titles={overview:['总览','查看宿主机网络代理状态'],subscription:['订阅','导入并维护 Mihomo 兼容配置'],nodes:['节点与规则','管理代理组、节点和运行模式'],network:['网络与安全','检查 TUN 保护和覆盖范围'],diagnostics:['诊断','查看脱敏日志和网络状态']};
function notice(message,success=false){const n=el('notice');n.textContent=message;n.classList.remove('hidden');n.classList.toggle('success',success);clearTimeout(notice.timer);notice.timer=setTimeout(()=>n.classList.add('hidden'),7000)}
async function api(op,data){const get=op==='status'||op==='diagnostics'||op==='connectivity'||op==='verify';const response=await fetch(base+op,{method:get?'GET':'POST',credentials:'same-origin',headers:get?{}:{'Content-Type':'application/json','X-FNVPN-Request':'1'},body:get?undefined:JSON.stringify(data||{})});const type=response.headers.get('Content-Type')||'';if(!type.toLowerCase().includes('application/json')){if(response.redirected)throw Error('fnOS 登录会话可能已过期，请重新登录');throw Error(`管理接口返回 HTTP ${response.status}，响应格式异常`)}let body;try{body=await response.json()}catch{throw Error(`管理接口响应无法解析（HTTP ${response.status}）`)}if(!response.ok||!body?.ok)throw Error(body?.error||`操作失败（HTTP ${response.status}）`);return body.data}
function setBusy(value){busy=value;document.querySelectorAll('button').forEach(button=>{if(!button.dataset.tab)button.disabled=value})}
function setText(id,value){el(id).textContent=value??'—'}
function ruleSummary(s){return s.source_rule_count>0?`订阅规则 ${s.rule_count||0}/${s.source_rule_count} 条${s.skipped_rule_count?`（跳过 ${s.skipped_rule_count}）`:''}`:'内置分流规则'}
function render(s){state=s;const running=!!s.running;el('side-dot').classList.toggle('on',running);setText('side-text',running?'TUN 已运行':'TUN 已关闭');setText('header-status',running?'运行中':'已关闭');el('header-status').className='chip '+(running?'on':'off');setText('hero-title',running?'系统 TUN 已开启':'系统 TUN 已关闭');setText('hero-desc',running?'已启用宿主机网络分流。网络异常时请使用右侧恢复按钮。':'首次启动保持关闭。导入可用配置后才能开启。');setText('core-state',running?'运行中':'未运行');setText('core-version',s.core_version);setText('tun-state',running?'已开启':'已关闭');setText('mode-state',({rule:'规则',global:'全局',direct:'直连'})[s.mode]||s.mode);setText('node-state',s.selected?.[s.selected_group]||'未选择');setText('group-state',s.selected_group||'节点选择');setText('update-time',s.last_update?new Date(s.last_update).toLocaleString():'从未更新');setText('source-state',s.source);setText('error-state',s.last_error||'无');setText('confirm-state',s.checks?.management_confirmation?'已确认':'等待页面确认');setText('dns-state',s.checks?.dns||'检查中');setText('sub-summary',`${s.source} · ${s.nodes?.length||0} 个节点 · ${ruleSummary(s)} · 最近成功 ${s.last_update?new Date(s.last_update).toLocaleString():'无'}`);setText('host-coverage',running?'待宿主机出口检测':'未开启');el('start').disabled=busy||running||!s.configured;el('stop').disabled=busy||!running;el('update').disabled=busy||s.source!=='已保存 HTTPS 地址';const prevGroup=el('group').value;el('group').replaceChildren(...(s.groups||[]).map(v=>new Option(v,v)));el('group').value=(s.groups||[]).includes(prevGroup)?prevGroup:s.selected_group;renderNodes();document.querySelectorAll('input[name=mode]').forEach(r=>r.checked=r.value===s.mode)}
function renderNodes(){if(!state)return;const group=el('group').value;const nodes=group==='节点选择'?state.nodes:(state.group_nodes?.[group]||state.nodes);el('node').replaceChildren(...nodes.map(v=>new Option(v,v)));if(state.selected?.[group])el('node').value=state.selected[group]}
async function refresh(){try{render(await api('status'))}catch(e){notice(e.message)}}
async function action(op,data,success){if(busy)return false;try{setBusy(true);const result=await api(op,data);if(op==='start'){await api('confirm');notice('TUN 已开启，管理页面连接已确认',true)}else notice(result?.import_notice?`${success||'操作完成'}；${result.import_notice}`:success||'操作完成',true);if(result)render(result);await refresh();return true}catch(e){notice(e.message);return false}finally{setBusy(false);if(state)render(state)}}
function toBase64(bytes){let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s)}
el('nav').addEventListener('click',event=>{const button=event.target.closest('button[data-tab]');if(!button)return;const tab=button.dataset.tab;document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===tab));setText('page-title',titles[tab][0]);setText('page-subtitle',titles[tab][1]);if(tab==='diagnostics')loadDiagnostics()});
el('start').onclick=()=>action('start',{},'TUN 已开启');el('stop').onclick=()=>action('stop',{},'已停止代理并恢复网络');el('recover').onclick=()=>action('recover',{},'已执行网络恢复');
el('toggle-url').onclick=()=>{const input=el('source-url');input.type=input.type==='password'?'text':'password';el('toggle-url').textContent=input.type==='password'?'显示输入':'隐藏输入'};
el('import-url').onclick=async()=>{const url=el('source-url').value.trim();if(!url){notice('请输入订阅 URL');return}if(await action('import-url',{url},'订阅已校验并保存'))el('source-url').value=''};
el('source-file').onchange=()=>setText('file-name',el('source-file').files[0]?.name||'未选择文件 · 最大 2 MiB');
el('import-file').onclick=async()=>{const file=el('source-file').files[0];if(!file){notice('请选择 YAML 文件');return}if(file.size>2*1024*1024){notice('文件超过 2 MiB');return}const bytes=new Uint8Array(await file.arrayBuffer());await action('import-file',{content:toBase64(bytes)},'配置已校验并保存')};
el('update').onclick=()=>action('update',{},'订阅已更新');el('group').onchange=renderNodes;el('save-node').onclick=()=>action('select',{group:el('group').value,node:el('node').value},'节点已应用');el('save-mode').onclick=()=>{const mode=document.querySelector('input[name=mode]:checked')?.value;if(mode)action('mode',{mode},'模式已应用')};
function renderConnectivity(data){const root=el('connectivity-result');root.replaceChildren();if(!data){root.textContent='尚未测试。开启 TUN 后点击“测试宿主机连接”。';return}const intro=document.createElement('p');intro.className='muted';intro.textContent=`测试时间：${new Date(data.checked_at).toLocaleString()} · TUN ${data.running?'运行中':'未运行'} · 接口 ${data.tun_interface?'已存在':'缺失'} · 路由规则 ${data.policy_rule?'已存在':'缺失'} · 路由表 ${data.tun_route_table?'已存在':'缺失'}`;root.append(intro);renderPublicRoute(root,data.public_route);const table=document.createElement('table');table.className='connectivity-table';const head=document.createElement('thead');const row=document.createElement('tr');for(const title of ['站点','连接','普通路由','指定 NAS 地址','耗时']){const cell=document.createElement('th');cell.textContent=title;row.append(cell)}head.append(row);table.append(head);const body=document.createElement('tbody');for(const item of data.sites||[]){const tr=document.createElement('tr');const values=[`${item.name} · ${item.host}${item.target_ipv4?' · '+item.target_ipv4:''}`,item.reachable?`已连接 · HTTP ${item.http_status}`:item.error||'未连接',item.route_interface||'未知',item.lan_route_interface||'未知',`${item.duration_ms} ms`];for(const value of values){const td=document.createElement('td');td.textContent=value;tr.append(td)}body.append(tr)}table.append(body);const wrap=document.createElement('div');wrap.className='connectivity-scroll';wrap.append(table);root.append(wrap);renderDNS(root,data.dns_checks);const guidance=document.createElement('p');guidance.className='connectivity-guidance';guidance.textContent=data.guidance||'';root.append(guidance);const scope=document.createElement('p');scope.className='muted';scope.textContent=data.scope||'';root.append(scope)}
function renderPublicRoute(root,route){if(!route)return;const line=document.createElement('p');line.className='muted';line.textContent=`公网 IP ${route.target} 路由：普通请求 ${route.route_interface||'未知'} · 指定 NAS 地址 ${route.lan_route_interface||'未知'}`;root.append(line)}
function renderDNS(root,checks){if(!Array.isArray(checks))return;const section=document.createElement('div');section.className='dns-probes';const title=document.createElement('h4');title.textContent='DNS 分段检测';section.append(title);for(const item of checks){const row=document.createElement('div');row.className='status-row';const name=document.createElement('span');name.textContent=item.name;const result=document.createElement('b');result.textContent=`${item.reachable?'已应答':item.error||'未应答'} · ${item.route_interface||'未知路由'} · ${item.duration_ms} ms`;row.append(name,result);section.append(row)}root.append(section)}
async function loadDiagnostics(){try{report=await api('diagnostics');el('diag-output').textContent=JSON.stringify(report,null,2);renderConnectivity(report.connectivity)}catch(e){notice(e.message)}}
el('run-connectivity').onclick=async()=>{if(busy)return;try{setBusy(true);el('connectivity-result').textContent='正在从飞牛主机连接 YouTube、Google、GitHub、百度…';const result=await api('connectivity');renderConnectivity(result);await loadDiagnostics()}catch(e){notice(e.message);el('connectivity-result').textContent='连接测试未完成：'+e.message}finally{setBusy(false);if(state)render(state)}};
el('refresh-diag').onclick=loadDiagnostics;el('copy-diag').onclick=async()=>{if(!report)await loadDiagnostics();if(report){await navigator.clipboard.writeText(JSON.stringify(report,null,2));notice('诊断报告已复制',true)}};el('download-diag').onclick=async()=>{if(!report)await loadDiagnostics();if(!report)return;const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='fnproxy-diagnostics.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
el('verify').onclick=async()=>{try{el('verify').disabled=true;const result=await api('verify');setText('exit-result',result.error||`宿主机出口 IP：${result.ip} · ${result.running?'TUN 运行中':'TUN 未开启'} · ${new Date(result.checked_at).toLocaleString()}`);if(result.error)notice(result.error)}catch(e){notice(e.message)}finally{el('verify').disabled=false}};
refresh();setInterval(refresh,6000);
